import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";
import Appbar from "./components/Appbar";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Hub",
  description: "Generated by create next app",
};
  
function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return ( 
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        
        <Provider>
          <Appbar></Appbar>
          <main className="flex-1">{children}</main>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
export default RootLayout
